### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers.models.bert.modeling_dpbert'

### ISSUE THREAD

**Issue by lifeformg** [JHA-Lab/acceltran#7]
When running `python3 run_evaluation.py --task sst2 --max_pruning_threshold 0.1`, this error occurs. I checked `transformers.models.bert`, and there is no `modeling_dpbert` here.

**Comment by shikhartuli** [comment]
Thanks for raising the issue! There was a minor name resolution bug that has been fixed in the latest commit.

**Comment by shikhartuli** [comment]
Marking as closed.
